### PR TITLE
Setup MongoDB

### LINKED ISSUE #2: Setup MongoDB
PR must include:-

- [ ] modular code for connecting db
- [ ] create .env.example file for reference to create .env file for running in local
- [ ] Should show connected to db log on starting server.
- [ ] everything should be done in src folder

### PR DESCRIPTION
**Pull request by anshul-132002**
PR must include:-

- [x] Modular code for connecting to the database in the `src` folder.
- [x] Create a `.env.example` file in the `src` folder for reference when creating the `.env` file for local development.
- [x] Log a "Connected to the database" message when starting the server.
- [x] Organize all code and files within the `src` folder.

Full Mongo DB setup in the src folder with .env file 
Fixes #2

### CODE REVIEW

**Comment by iammadanlal** [comment]
@anshul-132002 

where is .env.example file and you should not commit the .env file.
Also where is your db connection code.
Also package.json always be outside of src, only code part should in src.
.env.example file also should be outside src."

Please fix this and I will merge your code.

**Comment by anshul-132002** [comment]
@iammadanlal  I have fix the issue now please merge my request

**Comment by iammadanlal** [comment]
@anshul-132002 Can you please resolve the conflicts?

**Comment by anshul-132002** [comment]
@iammadanlal 
i have resolve conflicts in package.json

**Review by iammadanlal — APPROVED** [review]

**Comment by iammadanlal** [comment]
@anshul-132002 Can you please give a favor to repo by giving star and following me for time, I am putting?

**Pull request merged**
